---
- name: environment setup for linux & windows servers
  hosts: localhost
  gather_facts: true
  become: yes
  # Setup steps > Linux Control/Remote Machine > Windows Remote Machine 
  # > Packages are installed on remote linux machine
  # The playbook is ran from remote linux machine

  vars: 
    repo_url: "https://c-poteat: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@github.com/c-poteat/linux_server_setup.git"
    local_path: "/tmp/linux_server_setup"
    github_branch: "main"
    tar_files: "{{ local_path }}/winrm_tar_files"
    packages_to_install:
      - ansible-collection-redhat-rhel_mgmt
      - dos2unix
      - git
      - git-core-doc
      - nano
      - python38
      - python3-netaddr
      - rsync
      - tree
      - vim-common
      - vim-enhanced

  tasks: 
    - name: clone linux environment setup repo
      git: 
        repo: "{{ repo_url }}"
        dest: "{{ local_path }}"
        version: "{{ github_branch }}"
        clone: yes
        force: yes
      tags: 
        - clone_repo

    - name: update folder permissions
      file: 
        path: "{{ tar_files }}"
        mode: "0755"
        recurse: yes

    - name: run bash script from remote server
      command: /bin/bash /tmp/linux_server_setup/env_start.sh
      tags:
        - bash_install

    - name: remove python36 packages
      dnf: 
        name: python36
        state: absent
      tags: 
        - remove_python36

    - name: install packages via yum command
      yum: 
        name: "{{ item }}"
      loop: "{{ packages_to_install }}"
      tags:
        - yum_install

    - name: find tar files to extract
      find:
        paths: "{{ tar_files }}"
        patterns: "*.tar.gz"
      register: found_files
      tags: 
        - find_tar

    - name: extract tar files
      unarchive: 
        src: "{{ item.path }}"
        dest: "{{ tar_files }}"
        remote_src: yes
      loop: "{{ found_files.files }}"
      tags: 
        - extract_tar

    - name: list extracted folders
      find: 
        paths: "{{ tar_files }}"
        recurse: no
        file_type: directory
      register: extracted_folders
      tags: 
        - list_tar

    - name: install python packages
      command: >
        python3 setup.py install
      args: 
        chdir: "{{ item }}"
      with_items: 
        - /tmp/winrm_tar_files/certifi-2023.11.17
        - /tmp/winrm_tar_files/configobj-5.0.6
        - /tmp/winrm_tar_files/file-magic-0.3.0
        - /tmp/winrm_tar_files/PyJWT-1.6.1
        - /tmp/winrm_tar_files/PyYAML-6.0.1
        - /tmp/winrm_tar_files/six-1.11.0
        - /tmp/winrm_tar_files/webencodings-0.5.1
        - /tmp/winrm_tar_files/html5lib-0.999999999
        - /tmp/winrm_tar_files/jsonpointer-1.10
        - /tmp/winrm_tar_files/jsonpatch-1.21
        - /tmp/winrm_tar_files/ntlm-auth-1.5.0
        - /tmp/winrm_tar_files/oauthlib-2.1.0
        - /tmp/winrm_tar_files/ptyprocess-0.5.2
        - /tmp/winrm_tar_files/pexpect-4.3.1
        - /tmp/winrm_tar_files/pyserial-3.1.1
        - /tmp/winrm_tar_files/xmltodict-0.13.0
        - /tmp/winrm_tar_files/requests-2.20.0
        - /tmp/winrm_tar_files/requests_ntlm-1.1.0
        - /tmp/winrm_tar_files/pywinrm-0.4.3
      tags: 
        - py_packages